@DocumentManagementSystem.TenantManagementService_HostAddress = http://localhost:5101

GET {{DocumentManagementSystem.TenantManagementService_HostAddress}}/weatherforecast/
Accept: application/json

###
