name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore KhawarizMind.sln
      - name: Build & Test
        run: dotnet test KhawarizMind.sln --no-restore

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: KhawarizMind-frontend/package-lock.json
      - name: Install dependencies
        working-directory: KhawarizMind-frontend
        run: npm ci
      - name: Run tests
        working-directory: KhawarizMind-frontend
        run: npm test -- --watchAll=false
      - name: Run lint
        working-directory: KhawarizMind-frontend
        run: npm run lint
